databases:
  - name: ai-news-aggregator-db
    databaseName: ai_news_aggregator
    user: ai_news_user
    plan: free

services:
  - type: cron
    name: daily-digest-job
    env: docker
    dockerfilePath: ./Dockerfile
    schedule: "0 0 * * *"
    dockerCommand: python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-news-aggregator-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: MY_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false

